live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
# decorations = "buttonless"
startup_mode = "maximized"
dynamic_padding = false
opacity = 0.9

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

# TokyoNight Alacritty Colors
# Default colors
# [colors.primary]
# background = '#1a1b26'
# foreground = '#c0caf5'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#1a1b26'

# Normal colors
# [colors.normal]
# black = '#15161e'
# red = '#f7768e'
# green = '#9ece6a'
# yellow = '#e0af68'
# blue = '#7aa2f7'
# magenta = '#bb9af7'
# cyan = '#7dcfff'
# white = '#a9b1d6'
#
# # Bright colors
# [colors.bright]
# black = '#414868'
# red = '#f7768e'
# green = '#9ece6a'
# yellow = '#e0af68'
# blue = '#7aa2f7'
# magenta = '#bb9af7'
# cyan = '#7dcfff'
# white = '#c0caf5'
#
# # Indexed Colors
# [[colors.indexed_colors]]
# index = 16
# color = '#ff9e64'
#
# [[colors.indexed_colors]]
# index = 17
# color = '#db4b4b'

# Nord Alacritty Colors
# [colors.primary]
# background = '#2e3440'
# foreground = '#d8dee9'
# dim_foreground = '#a5abb6'
#
# [colors.cursor]
# text = '#2e3440'
# cursor = '#d8dee9'
#
# [colors.vi_mode_cursor]
# text = '#2e3440'
# cursor = '#d8dee9'
# #
# [colors.normal]
# black = '#3b4252'
# red = '#bf616a'
# green = '#a3be8c'
# yellow = '#ebcb8b'
# blue = '#81a1c1'
# magenta = '#b48ead'
# cyan = '#88c0d0'
# white = '#e5e9f0'
#
# [colors.bright]
# black = '#4c566a'
# red = '#bf616a'
# green = '#a3be8c'
# yellow = '#ebcb8b'
# blue = '#81a1c1'
# magenta = '#b48ead'
# cyan = '#8fbcbb'
# white = '#eceff4'
#
# [colors.dim]
# black = '#373e4d'
# red = '#94545d'
# green = '#809575'
# yellow = '#b29e75'
# blue = '#68809a'
# magenta = '#8c738c'
# cyan = '#6d96a5'
# white = '#aeb3bb'

# Rose Pine Alacritty Colors
[colors.primary]
foreground = "#e0def4"
background = "#191724"
dim_foreground = "#908caa"
bright_foreground = "#e0def4"

[colors.cursor]
text = "#e0def4"
cursor = "#524f67"

[colors.vi_mode_cursor]
text = "#e0def4"
cursor = "#524f67"

[colors.search.matches]
foreground = "#908caa"
background = "#26233a"

[colors.search.focused_match]
foreground = "#191724"
background = "#ebbcba"

[colors.hints.start]
foreground = "#908caa"
background = "#1f1d2e"

[colors.hints.end]
foreground = "#6e6a86"
background = "#1f1d2e"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#e0def4"
background = "#1f1d2e"

[colors.selection]
text = "#e0def4"
background = "#403d52"

[colors.normal]
black = "#26233a"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"

[colors.bright]
black = "#6e6a86"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"

[colors.dim]
black = "#6e6a86"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"
